setwd("D:")
getwd()
set.seed(6)
library(rpart)
library(magrittr)
library(caret)
library(e1071)
#install.packages("partykit")
library("partykit")
install.packages("party")
library("party")
library(dplyr)
a<-read.csv("titanic_train.csv")
View(a)
colSums(is.na(a))
b<-na.omit(b)
r<-createDataPartition(b$survived,p=0.8,list=FALSE)
train<-b[r,]
test<-b[-r,]

#CART
#install.packages("rattle")
library(rattle)
model1<-rpart(factor(survived)~., a[,-c(1,3,7,9,8,13,11,12,10,14)])
fancyRpartPlot(model1)
plotcp(model1)
L<-predict(model1,test,"prob")
class1<-ifelse(L[,2]>0.5,1,0)
confusionMatrix(factor(test$survived),factor(class1))
#///////conditional inference tree
model2<-prune(model1,0.15)
fancyRpartPlot(model2)
model3<-ctree(factor(survived)~.,a[,-c(1,3,7,9,8,13,11,12,10,14)])
plot(model3)
M<-predict(model3,test,"prob")
class2<-ifelse(M[,2]>0.5,1,0)
confusionMatrix(factor(test$survived),factor(M))
#c5.0
#install.packages("C50")
library(C50)
model4<-C50::C5.0.formula(factor(survived)~., a[,-c(1,3,7,9,8,13,11,12,10,14)],)
N<-predict(model4,test,"prob",trials = 1)
class3<-ifelse(N[,2]>0.5,1,0)
confusionMatrix(factor(test$survived),factor(class3))
#randomforest
install.packages("randomForest")
library(randomForest)
model5<-randomForest(factor(survived)~., a[,-c(1,3,7,9,8,13,11,12,10,14)], mtry=3)
model5<-randomForest(factor(survived)~., a[,-c(1,3,5,7,9,8,13,11,12,10,14)], mtry=3,ntree=200)
plot(model5)
varImpPlot(model5)
O<-predict(model5,test,"prob")
class4<-ifelse(O[,2]>0.5,1,0)
confusionMatrix(factor(test$survived),factor(class4))

